// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duooueclvdhebpyrsqxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1b291ZWNsdmRoZWJweXJzcXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMjk0ODEsImV4cCI6MjA1MjYwNTQ4MX0.3CLal0-xOFbv8fSMyzQ78GsK31p1Ax3Bf-bKUA-R6Vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);